# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-23 19:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('item_text', models.CharField(max_length=255, verbose_name=b'Titulo del item')),
                ('slug', models.CharField(blank=True, max_length=255, null=True)),
                ('url', models.URLField(blank=True, null=True, verbose_name=b'URL alternativa')),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('wrap_tag', models.CharField(default=b'li', max_length=255, verbose_name=b'Tag HTML')),
                ('class_tag', models.CharField(blank=True, default=b'', max_length=255, null=True, verbose_name=b'Class')),
                ('attrs_tag', models.CharField(blank=True, max_length=255, null=True, verbose_name=b'Atributos')),
                ('link_to_email', models.CharField(blank=True, help_text=b'Para tomar este link dejar campo URL y objetos relacionados vacios', max_length=255, null=True, verbose_name=b'Link a Mail')),
                ('is_link', models.BooleanField(default=True, verbose_name=b'Es link')),
                ('link_target', models.CharField(blank=True, choices=[(None, 'nada'), (b'_blank', 'Nueva pesta\xf1a'), (b'_new', 'Nueva ventana'), (b'_top', 'Arriba')], max_length=40, null=True, verbose_name=b'Modo de apertura')),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='contenttypes.ContentType')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu_text', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255, null=True)),
                ('wrap_tag', models.CharField(default=b'ul', max_length=255, verbose_name=b'Tag HTML')),
                ('class_tag', models.CharField(blank=True, default=b'', max_length=255, null=True, verbose_name=b'Class')),
                ('attrs_tag', models.CharField(blank=True, default=b'', max_length=255, null=True, verbose_name=b'Atributos')),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='menu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='menuresolver.Menu'),
        ),
    ]
